version: 2

jobs:
  build:
    docker:
      - image: cimg/go:1.19.5
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get -y -qq install python3 python3-pip
      - run: pip3 install pre-commit
      - run: SKIP=no-commit-to-branch pre-commit run -a
      - run: go test ./...
      - run: make test
