# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
archives:
  - id: revive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
before:
  hooks:
    - "go mod download"
    - "go generate ./..."
builds:
  -
    env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "ghcr.io/mgechev/revive:{{ .Version }}"
      - "ghcr.io/mgechev/revive:{{ .Tag }}"
      - "ghcr.io/mgechev/revive:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/mgechev/revive:v{{ .Major }}"
      - "ghcr.io/mgechev/revive:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - "--label=org.opencontainers.image.description=🔥 ~6x faster, stricter, configurable, extensible, and beautiful drop-in replacement for golint"
      - --label=org.opencontainers.image.url=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.source=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
project_name: revive
