version: '3'

tasks:
  default:
    sources:
    - "./**/*.go"
    method: timestamp
    cmds:
    - clear
    - make build
    - ls -lah bin/ireturn
    # - task: testcase
    #   vars: {Case: "zero:_Empty_Package_With_No_Issues"}
    - make tests
    - make lints
  testcase: go test -v -failfast -count=1 -run "TestAll/{{ .Case }}" ./...
