version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - unconvert
    - unparam
