run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - gofmt
    - goimports
    - ineffassign
    - staticcheck
    - unused
    - gosimple

issues:
  exclude-use-default: false
