// generated by compile -asmhdr from package lz4block

#define const_minMatch 4
#define const_winSizeLog 16
#define const_winSize 65536
#define const_winMask 65535
#define const_hashLog 16
#define const_htSize 65536
#define const_mfLimit 14
#define Compressor__size 139264
#define Compressor_table 0
#define Compressor_inUse 131072
#define CompressorHC__size 1048584
#define CompressorHC_hashTable 0
#define CompressorHC_chainTable 524288
#define CompressorHC_needsReset 1048576
#define const_Block64Kb 65536
#define const_Block256Kb 262144
#define const_Block1Mb 1048576
#define const_Block4Mb 4194304
#define const_Block8Mb 8388608
#define const_Fast 0
