version: 2.1

orbs:
  go-module: timakin/go-module@0.3.0
  golangci-lint: timakin/golangci-lint@0.1.0

executors:
  default:
    working_directory: /go/src/github.com/timakin/bodyclose
    docker:
    - image: circleci/golang:1.12
    environment:
    - APP_NAME: bodyclose
    - GO111MODULE: "on"

jobs:
  test:
    executor:
      name: default
    steps:
    - attach_workspace:
        at: /go/src/github.com/timakin/bodyclose
    - run: go test ./...

workflows:
  version: 2
  setup_and_deploy:
    jobs:
    - go-module/download:
        executor: default
        checkout: true
        vendoring: true
        persist-to-workspace: true
        workspace-root: /go/src/github.com/timakin/bodyclose
    - test:
        requires:
        - go-module/download
    - golangci-lint/lint:
        checkout: false
        attach-workspace: true
        workspace-root: /go/src/github.com/timakin/bodyclose
        working-directory: /go/src/github.com/timakin/bodyclose
        requires:
        - go-module/download
        filters:
          branches:
            ignore:
            - master
