name: Publish Docs

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - docs/**
  workflow_run:
    workflows: ["Release Production"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  actions: read

env:
  GO_VERSION: 1.25.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set executable permissions for script
        run: chmod +x ./scripts/generate-service-config-docs.sh

      - name: Generate Service Config Docs
        run: |
          go mod download
          go clean -cache  # Clear build cache
          ./scripts/generate-service-config-docs.sh

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: "3.13.7"
          cache: "pip"
          cache-dependency-path: |
            build/mkdocs/docs-requirements.txt

      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"

      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs
        run: |
          pip install -r build/mkdocs/docs-requirements.txt

      - name: Build and Deploy
        run: mkdocs gh-deploy --force --verbose --config-file build/mkdocs/mkdocs.yaml
