name: Run tests and upload coverage

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.25.x
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -v -coverprofile coverage.out -covermode atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@3cb13a12348ef4ffcf9783ac0f74954f92113e33
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
