name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build gofmt
        run: go build ./gofmt
      - name: Build goimports
        run: go build ./goimports
