language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
  - go get github.com/mattn/goveralls

script:
  - go test -cpu=2 -race -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
