name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1'

      - uses: actions/checkout@v4

      - name: Build
        run: GOEXPERIMENT=coverageredesign go build -cover -v ./cmd/gosmopolitan

      - name: Test
        run: ./ci/run.sh
