name: Run tests

on:
  push:
    branches:
      - main
    tags:
      - v3.*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [stable, oldstable]

    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set PATH
        run: echo "${GITHUB_WORKSPACE}/.local/bin" >>"${GITHUB_PATH}"

      - if: matrix.go == 'stable' && matrix.os == 'ubuntu-latest'
        run: make ensure-goimports

      - if: matrix.go == 'stable' && matrix.os == 'ubuntu-latest'
        run: make lint

      - run: make vet
      - run: make test
      - run: make check-binary-size

      - if: matrix.go == 'stable' && matrix.os == 'ubuntu-latest'
        run: make generate

      - run: make diffcheck

      - if: matrix.go == 'stable' && matrix.os == 'ubuntu-latest'
        run: make v3diff

      - if: success() && matrix.go == 'stable' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
