on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - '1.19.x'
        - '1.20.x'
        os:
        - ubuntu-latest
        - macos-11
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: |
        go test ./...
        go test -race ./...

    - name: Tidy
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.20.x' # no need to do this everywhere
      run: |
        go mod tidy

        test -z "$(gofmt -d .)" || (gofmt -d . && false)
        test -z "$(git status --porcelain)" || (git status; git diff && false)
