# Inspired by github.com/IBM/sarama/pull/2874 (MIT)

name: i386

on:
  push:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'

jobs:
  atomicalign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: staticcheck
        env:
          GOARCH: 386
          GOFLAGS: -tags=functional
        run: |
            git clone --depth=1 https://github.com/dominikh/go-tools /tmp/go-tools
            ( cd /tmp/go-tools/cmd/staticcheck && go build -o /tmp/staticcheck )
            /tmp/staticcheck -checks SA1027 ./...
