---
name: Run Security Checks
on:
  pull_request:
    branches: [main]
    paths:
      - internal/**
      - pkg/**
      - shoutrrr/**
      - go.mod
      - go.sum
      - shoutrrr.go
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  pull-requests: read
  security-events: write

env:
  GO_VERSION: 1.25.x
  OUTPUT_FILE: results.sarif

jobs:
  gosec:
    name: Golang Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run Gosec Security Scanner
        uses: securego/gosec@506407e7dfe6979d514d362f0b2d2ea77f49f5c8
        with:
          args: "-no-fail -fmt sarif -out results.sarif -tests ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: nicholas-fedor/govulncheck-action@1e9ef2cbd93abefcc8605e05f8c212aa90181f6f
        with:
          output-format: sarif
          output-file: ${{ env.OUTPUT_FILE }}
          go-version-input: ${{ env.GO_VERSION }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3
        with:
          sarif_file: ${{ env.OUTPUT_FILE }}
