name: Run tests and upload coverage

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.25.x
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -v -coverprofile coverage.out -covermode atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
