// generated by compile -asmhdr from package xxhash

#define const_prime1 11400714785074694791
#define const_prime2 14029467366897019727
#define const_prime3 1609587929392839161
#define const_prime4 9650029242287828579
#define const_prime5 2870177450012600261
#define Digest__size 80
#define Digest_v1 0
#define Digest_v2 8
#define Digest_v3 16
#define Digest_v4 24
#define Digest_total 32
#define Digest_mem 40
#define Digest_n 72
#define const_magic "xxh\x06"
#define const_marshaledSize 76
