name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.20.6

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21', '1.22' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Test
        run: go test -v -race ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          args: --timeout 5m

  tests-on-windows:
    needs: run
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Test
        run: go test -v -race ./...

  tests-on-macos:
    needs: run 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Test
        run: go test -v -race ./...
