name: "Post release"
on:
  release:
    types:
      - published

jobs:
  install:
    name: Install script
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest] # windows has a problem when curl use `%{http_code}`, it returns 000 instead of 200.
    runs-on: ${{ matrix.os }}

    steps:
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/misspell/master/install-misspell.sh | sh -s -- -b "./bin-misspell"
