name: golangci-lint

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.22', '1.23']
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
